--- #YAML:1.0
name:               WWW-Vimeo-Simple
version:            0.03
abstract:           Object-oriented Vimeo Simple API interface.
author:
    - Alessandro Ghedini <alexbio@cpan.org>
license:            perl
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    HTTP::Request::Common:  0
    JSON:                 0
    LWP::UserAgent:       0
    Test::More:           0
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.55_02
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
